import 'package:flutter/material.dart';

class AppModel {
  final String name, image, description, category;
  final double rating;
  final int review, price;
  List<Color> fcolor;
  List<String> size;
  bool isCheck;

  AppModel({
    required this.name,
    required this.image,
    required this.rating,
    required this.review,
    required this.fcolor,
    required this.size,
    required this.description,
    required this.isCheck,
    required this.category,
    required this.price,
  });
}

List<AppModel> fashionEcommerceApp = [
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
  AppModel(
      name: 'Oversized fit Printed Mesh T-Shirt',
      image: "assets/shirt.png",
      rating: 4.9,
      review: 136,
      price: 295,
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "",
      isCheck: true,
      category: "Women"),
];

const myDescription1 = "Elevate your casual wardrobe with our";
const myDescription2 = "Elevate your casual wardrobe with our";
